model_name: alexnet_mv_max_color
model_to_use: alexnet_mv_max_color
backbone_path: C:\Users\15B38LA\Downloads\alexnet_all.ckpt

image_path: C:\Users\15B38LA\Downloads\section_w256
num_classes:  6

min_exec_epochs: 1
max_exec_epochs: 1

image_mean: "0.659, 0.587, 0.482"
image_std:  "0.1303, 0.132, 0.133"
are_images_gray: "no"

manualSeed: 0
use_augmentation: True
save_model: True